#:schema https://json.schemastore.org/prettierrc

experimentalOperatorPosition = "start"
experimentalTernaries = false
htmlWhitespaceSensitivity = "ignore"
plugins = [
	"prettier-plugin-organize-imports",
	"prettier-plugin-pkg",
	"prettier-plugin-sh",
	"prettier-plugin-toml",
	"prettier-plugin-tailwindcss",
]
printWidth = 100
proseWrap = "always"
semi = false
useTabs = true


alignComments = true
alignEntries = false
allowedBlankLines = 2
arrayAutoCollapse = true
arrayAutoExpand = true
compactArrays = true
compactEntries = false
compactInlineTables = false
indentEntries = false
indentTables = false
reorderKeys = true


tailwindStylesheet = "./src/css/app.css"


[[overrides]]
files = ["package.json"]

[overrides.options]
parser = "json-stringify"


[[overrides]]
files = ["tsconfig.json"]

[overrides.options]
parser = "jsonc"
trailingComma = "none"


[[overrides]]
files = ["*.json", "*.md", "*.{yml,yaml}"]

[overrides.options]
useTabs = false
