[tools]
actionlint = "1.7"
bun = "1.2"
shellcheck = "0.10"


[tasks."default"]
hide = true
run = "mise tasks ls"


[tasks."dev"]
depends = ["deps:node"]
description = "run dev server"
run = "bun src/index.html"


[tasks."deploy"]
depends = ["build --minify"]
description = "build project for production"


[tasks."build"]
depends = ["deps:node"]
description = "build project"
run = "bun run build.ts"


[tasks."lint"]
depends = ["lint:*"]
description = "lint sources"

[tasks."lint:prettier"]
depends = ["deps:node"]
description = "check prettier formatting"
run = "bun x --bun prettier --check ."

[tasks."lint:tsc"]
depends = ["deps:node"]
description = "check typescript"
run = "bun x --bun tsc --noEmit"

[tasks."lint:actions"]
description = "check github actions"
run = "actionlint"


[tasks."fmt"]
depends = ["fmt:*"]
description = "apply automatic fixes"

[tasks."fmt:prettier"]
depends = ["deps:node"]
description = "fix prettier formatting"
run = "bun x --bun prettier --write ."


[tasks."deps"]
depends = ["deps:*"]
description = "fetch project dependencies"

[tasks."deps:node"]
description = "fetch node dependencies"
outputs = ["./node_modules/sentinel"]
run = ["bun install", "touch ./node_modules/sentinel"]
sources = ["./package.json", "./bun.lockb"]


[tasks."deps-up"]
depends = ["deps-up:*"]
description = "update project dependencies"

[tasks."deps-up:node"]
description = "update node dependencies"
run = ["bun update --latest", "bun install", "touch ./node_modules/sentinel"]


[tasks."ci:deps"]
depends = ["ci:deps:*"]
description = "fetch project dependencies in ci"

[tasks."ci:deps:node"]
description = "fetch node dependencies in ci"
outputs = ["./node_modules/sentinel"]
run = ["bun install --frozen-lockfile", "touch ./node_modules/sentinel"]
sources = ["./package.json", "./bun.lockb"]


[tasks."clean"]
depends = ["deps:node"]
description = "clean bundled site"
run = "bun x --bun rimraf _site/"
