---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: run lint checks

on:
  workflow_call:
    outputs:
      bun-cache:
        description: bun cache directory
        value: ${{ jobs.data.outputs.bun-cache }}

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: setup build tools
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: detect environment data
        id: data
        run: |
          echo "bun-cache=$(bun pm cache)" >> "$GITHUB_OUTPUT"

      - name: cache project dependencies
        uses: actions/cache@v4
        env:
          cache-name: bun-cache
        with:
          path: ${{ steps.data.outputs.bun-cache }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install dependencies
        run: mise run ci:deps
