---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: deploy to github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup build tools
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: detect data
        id: data
        run: |
          echo "bun-cache=$(bun pm cache)" >> "$GITHUB_OUTPUT"

      - name: cache project dependencies
        uses: actions/cache@v4
        env:
          cache-name: bun-cache
        with:
          path: ${{ steps.data.outputs.bun-cache }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install dependencies
        run: mise run ci:deps

      - name: lint sources
        run: mise run lint

      - name: build project
        run: mise run build

      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v3
